template_path: fargate/cluster/cluster.yaml
parameters:
  VpcId:  !stack_output {{ stack_group_config.env }}/vpc/vpc.yaml::VpcId
  VpcPublicSubnetsIds: !stack_output {{ stack_group_config.env }}/vpc/vpc.yaml::PublicSubnetsList
  Environment: {{ stack_group_config.env }}
  ClusterName: {{ stack_group_config.project_code }}
  PublicBalancer: "True"
