AWSTemplateFormatVersion: '2010-09-09'
Description: Template for a generic Fargate Task.
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description:  VPC Id
  VpcSubnetsIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'Choose at least two subnets in your selected VPC with the same type (Public or Private).'
  ClusterName:
    Type: String
    Default: ""
    Description: A user-generated string that you use to identify your cluster. If you don't specify a name, AWS CloudFormation generates a unique physical ID for the name.
  ClusterLogsGroup:
    Type: String
    Description: Logs Group for the task.
  ServiceName:
    Type: String
    Default: nginx
    Description: A name for the service.
  ImageUrl:
    Type: String
    Default: nginx
    Description: The url of a docker image that contains the application process that will handle the traffic for this service.
  ImageVersion:
    Type: String
    Default: latest
    Description: Define the Image version to use.
  ContainerPort:
    Type: Number
    Default: 80
    Description: What port number the application inside the docker container is binding to.
  ContainerCpu:
    Type: Number
    Default: 256
    Description: How much CPU to give the container. 1024 is 1 CPU.
  ContainerMemory:
    Type: Number
    Default: 512
    Description: How much memory in megabytes to give the container.
  Path:
    Type: String
    Default: "*"
    Description: A path on the public load balancer that this service should be connected to. Use * to send all load balancer traffic to this service.
  Priority:
    Type: Number
    Default: 1
    Description: The priority for the routing rule added to the load balancer. This only applies if your have multiple services which have been assigned to different paths on the load balancer.
  DesiredCount:
    Type: Number
    Default: 2
    Description: How many copies of the service task to run.
  Role:
    Type: String
    Default: ""
    Description: (Optional) An IAM role to give the service's containers if the code within needs to access other AWS resources like S3 buckets, DynamoDB tables, etc.
  PublicListenerArn:
    Type: String
    Description: Public Listener for Arn.
  ExecutionRoleArn:
    Type: String
    Description: ExecutionRoleArn
  FargateContainerSecurityGroup:
    Type: String
    Description: SecurityGroup Id for Fargate Containers.
  PlatformVersion:
    Type: String
    Default: LATEST
    Description: The platform version that your tasks in the service are running on.
  Environment:
    Type: String
    Description: The environment name.

Conditions:
  HasCustomRole: !Not [ !Equals [!Ref 'Role', ''] ]

Resources:

  # The task definition. This is a simple metadata description of what
  # container to run, and what resource requirements it has.
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref 'ServiceName'
      Cpu: !Ref 'ContainerCpu'
      Memory: !Ref 'ContainerMemory'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref 'ExecutionRoleArn'
      TaskRoleArn:
        Fn::If:
          - 'HasCustomRole'
          - !Ref 'Role'
          - !Ref "AWS::NoValue"
      ContainerDefinitions:
        - Name: !Ref 'ServiceName'
          Cpu: !Ref 'ContainerCpu'
          Memory: !Ref 'ContainerMemory'
          Image: !Join ['',[!Ref 'ImageUrl',':',!Ref 'ImageVersion']]
          PortMappings:
            - ContainerPort: !Ref 'ContainerPort'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              'awslogs-region': !Ref 'AWS::Region'
              'awslogs-group': !Ref 'ClusterLogsGroup'
              'awslogs-stream-prefix': 'tasks'

  # The service. The service is a resource which allows you to run multiple
  # copies of a type of task, and gather up their logs and metrics, as well
  # as monitor the number of running tasks and replace any that have crashed
  Service:
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerRule
    Properties:
      ServiceName: !Ref 'ServiceName'
      Cluster: !Ref 'ClusterName'
      PlatformVersion: !Ref PlatformVersion
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: !Ref 'DesiredCount'
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref 'FargateContainerSecurityGroup'
          Subnets:
          - !Select [0, !Ref VpcSubnetsIds]
          - !Select [1, !Ref VpcSubnetsIds]
          - !Select [2, !Ref VpcSubnetsIds]
      TaskDefinition: !Ref 'TaskDefinition'
      LoadBalancers:
        - ContainerName: !Ref 'ServiceName'
          ContainerPort: !Ref 'ContainerPort'
          TargetGroupArn: !Ref 'TargetGroup'

  # A target group. This is used for keeping track of all the tasks, and
  # what IP addresses / port numbers they have. You can query it yourself,
  # to use the addresses yourself, but most often this target group is just
  # connected to an application load balancer, or network load balancer, so
  # it can automatically distribute traffic across all the targets.
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: ip
      Name: !Ref 'ServiceName'
      Port: !Ref 'ContainerPort'
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref VpcId

  # Create a rule on the load balancer for routing traffic to the target group
  LoadBalancerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref 'TargetGroup'
          Type: 'forward'
      Conditions:
        - Field: path-pattern
          Values: [!Ref 'Path']
      ListenerArn: !Ref 'PublicListenerArn'
      Priority: !Ref 'Priority'

# These are the values output by the CloudFormation template.
Outputs:
  ServiceName:
    Description: The name of the service
    Value: !Ref 'ServiceName'
  ServiceArn:
    Description: The ARN of the service
    Value: !Ref 'Service'
  ImageUrl:
    Description: Image Url
    Value: !Ref 'ImageUrl'
